#ifndef ZANATA_ENUMS_H
#define ZANATA_ENUMS_H

G_BEGIN_DECLS

typedef enum
  {
    ZANATA_ERROR_UNKNOWN,
    ZANATA_ERROR_INVALID_RESPONSE
  }
ZanataError;

typedef enum
  {
    ZANATA_PROJECT_STATUS_UNKNOWN,
    ZANATA_PROJECT_STATUS_ACTIVE,
    ZANATA_PROJECT_STATUS_OBSOLETE
  }
ZanataProjectStatus;

typedef enum
  {
    ZANATA_ITERATION_STATUS_UNKNOWN,
    ZANATA_ITERATION_STATUS_READONLY,
    ZANATA_ITERATION_STATUS_OBSOLETE
  }
ZanataIterationStatus;

G_END_DECLS

#endif  /* ZANATA_ENUMS_H */
